#!/bin/bash
# MySQLセットアップ修正スクリプト

echo "=========================================="
echo "MySQL接続問題の解決方法"
echo "=========================================="
echo ""

echo "方法1: sudoでMySQLに接続してパスワードを確認/設定"
echo "以下のコマンドを実行してください:"
echo ""
echo "  sudo mysql -u root"
echo ""
echo "MySQLに接続できたら、以下を実行:"
echo ""
echo "  ALTER USER 'root'@'localhost' IDENTIFIED BY 'kikuoo100907';"
echo "  FLUSH PRIVILEGES;"
echo "  exit"
echo ""
echo "=========================================="
echo ""
echo "方法2: 新しいユーザーを作成"
echo "以下のコマンドを実行してください:"
echo ""
echo "  sudo mysql -u root"
echo ""
echo "MySQLに接続できたら、以下を実行:"
echo ""
echo "  CREATE USER 'notest_user'@'localhost' IDENTIFIED BY 'kikuoo100907';"
echo "  GRANT ALL PRIVILEGES ON *.* TO 'notest_user'@'localhost';"
echo "  FLUSH PRIVILEGES;"
echo "  exit"
echo ""
echo "その後、.envファイルを編集:"
echo "  MYSQL_USER=notest_user"
echo "  MYSQL_PASSWORD=kikuoo100907"
echo ""
echo "=========================================="
echo ""
echo "方法3: パスワードなしで接続できる場合"
echo "sudo mysqlで接続できる場合、.envファイルで:"
echo "  MYSQL_PASSWORD="
echo "として、sudo権限でアプリを起動する必要があります（非推奨）"
echo ""
echo "=========================================="
