#!/bin/bash
# MySQLユーザー作成スクリプト

echo "=========================================="
echo "Notest用MySQLユーザーを作成します"
echo "=========================================="
echo ""
echo "sudo mysqlで接続できる場合、以下のコマンドを実行してください:"
echo ""
echo "  sudo mysql -u root < create_mysql_user.sql"
echo ""
echo "または、対話的に:"
echo ""
echo "  sudo mysql -u root"
echo ""
echo "MySQLに接続したら、以下を実行:"
echo ""
echo "  CREATE USER 'notest_user'@'localhost' IDENTIFIED BY 'kikuoo100907';"
echo "  GRANT ALL PRIVILEGES ON *.* TO 'notest_user'@'localhost';"
echo "  FLUSH PRIVILEGES;"
echo "  exit;"
echo ""
echo "その後、.envファイルを編集して:"
echo "  MYSQL_USER=notest_user"
echo "  MYSQL_PASSWORD=kikuoo100907"
echo ""
echo "接続テスト:"
echo "  source venv/bin/activate"
echo "  python test_mysql_connection.py"
echo ""
